import { Song } from '../types'

export const MOCK_SONGS: Song[] = [
  // 华语经典 / 90S华语
  { id: 'c1', title: '颜色', artist: '许美静', album: '快乐无罪', emotionTags: ['慵懒', '夜晚'], sceneTags: ['深夜', '独处'], moodScore: 4, neteaseId: 'c1' },
  { id: 'c2', title: '取消资格', artist: '陈奕迅', album: 'The Easy Ride', emotionTags: ['伤感', '遗憾'], sceneTags: ['深夜', '失恋'], moodScore: 3, neteaseId: 'c2' },
  { id: 'c3', title: '一万一千公里', artist: '那英', album: '我不是天使', emotionTags: ['沧桑', '远行'], sceneTags: ['开车', '旅行'], moodScore: 5, neteaseId: 'c3' },
  { id: 'c4', title: '分分钟需要你', artist: '林子祥', album: '摩登土佬', emotionTags: ['甜蜜', '复古'], sceneTags: ['晴天', '恋爱'], moodScore: 8, neteaseId: 'c4' },
  { id: 'c5', title: '房间先醒', artist: 'naim宝宝', album: '房间', emotionTags: ['温暖', '慵懒'], sceneTags: ['早晨', '独处'], moodScore: 6, neteaseId: 'c5' },
  { id: 'c6', title: '一样的夏天', artist: '孙燕姿', album: 'Leave', emotionTags: ['青春', '怀念'], sceneTags: ['晴天', '回忆'], moodScore: 7, neteaseId: 'c6' },
  { id: 'c7', title: '梦伴', artist: '李悦君', album: '梦伴', emotionTags: ['复古', '浪漫'], sceneTags: ['深夜', '跳舞'], moodScore: 7, neteaseId: 'c7' },
  { id: 'c8', title: '月光浴', artist: '陈晓东', album: '比我幸福', emotionTags: ['温柔', '浪漫'], sceneTags: ['夜晚', '恋爱'], moodScore: 6, neteaseId: 'c8' },
  { id: 'c9', title: '晴天', artist: '周杰伦', album: '叶惠美', emotionTags: ['温暖', '治愈'], sceneTags: ['晴天', '午后'], moodScore: 7, neteaseId: 'c9' },
  { id: 'c10', title: '夜曲', artist: '周杰伦', album: '十一月的萧邦', emotionTags: ['忧郁', '深情'], sceneTags: ['深夜', '独处'], moodScore: 4, neteaseId: 'c10' },
  { id: 'c11', title: '稻香', artist: '周杰伦', album: '魔杰座', emotionTags: ['温暖', '治愈'], sceneTags: ['晴天', '乡村'], moodScore: 8, neteaseId: 'c11' },
  { id: 'c12', title: '平凡之路', artist: '朴树', album: '猎户星座', emotionTags: ['沧桑', '坚定'], sceneTags: ['开车', '旅行'], moodScore: 5, neteaseId: 'c12' },
  { id: 'c13', title: '成都', artist: '赵雷', album: '无法长大', emotionTags: ['怀旧', '民谣'], sceneTags: ['旅行', '咖啡馆'], moodScore: 6, neteaseId: 'c13' },
  { id: 'c14', title: '消愁', artist: '毛不易', album: '平凡的一天', emotionTags: ['怀旧', '感慨'], sceneTags: ['深夜', '独处'], moodScore: 3, neteaseId: 'c14' },
  { id: 'c15', title: '像我这样的人', artist: '毛不易', album: '平凡的一天', emotionTags: ['自嘲', '温柔'], sceneTags: ['深夜', '思考'], moodScore: 3, neteaseId: 'c15' },
  { id: 'c16', title: '大鱼', artist: '周深', album: '深的深', emotionTags: ['空灵', '悲伤'], sceneTags: ['深夜', '安静'], moodScore: 3, neteaseId: 'c16' },
  { id: 'c17', title: '起风了', artist: '买辣椒也用券', album: '起风了', emotionTags: ['感慨', '怀念'], sceneTags: ['傍晚', '独处'], moodScore: 5, neteaseId: 'c17' },
  { id: 'c18', title: '体面', artist: '于文文', album: '前任3', emotionTags: ['伤感', '释怀'], sceneTags: ['深夜', '失恋'], moodScore: 3, neteaseId: 'c18' },
  { id: 'c19', title: '往后余生', artist: '马良', album: '往后余生', emotionTags: ['深情', '承诺'], sceneTags: ['婚礼', '浪漫'], moodScore: 7, neteaseId: 'c19' },
  { id: 'c20', title: '年少有为', artist: '李荣浩', album: '耳朵', emotionTags: ['遗憾', '成长'], sceneTags: ['深夜', '回忆'], moodScore: 4, neteaseId: 'c20' },

  // 华语摇滚 / 独立
  { id: 'c21', title: '无人的海边', artist: '霓虹花园', album: '再见威尔逊', emotionTags: ['自由', '热烈'], sceneTags: ['运动', '开车'], moodScore: 8, neteaseId: 'c21' },
  { id: 'c22', title: '巫堵', artist: 'deca joins', album: '浴室', emotionTags: ['慵懒', '迷幻'], sceneTags: ['深夜', '独处'], moodScore: 4, neteaseId: 'c22' },
  { id: 'c23', title: '想去海边', artist: '夏日入侵企画', album: '想去海边', emotionTags: ['青春', '自由'], sceneTags: ['晴天', '旅行'], moodScore: 8, neteaseId: 'c23' },
  { id: 'c24', title: '晚安', artist: '丢火车', album: '晚安', emotionTags: ['温柔', '告别'], sceneTags: ['深夜', '独处'], moodScore: 3, neteaseId: 'c24' },
  { id: 'c25', title: '水星记', artist: '郭顶', album: '飞行器的执行周期', emotionTags: ['孤独', '仰望'], sceneTags: ['深夜', '独处'], moodScore: 3, neteaseId: 'c25' },
  { id: 'c26', title: '保留', artist: '郭顶', album: '飞行器的执行周期', emotionTags: ['遗憾', '珍藏'], sceneTags: ['雨天', '独处'], moodScore: 3, neteaseId: 'c26' },
  { id: 'c27', title: '麻雀', artist: '李荣浩', album: '麻雀', emotionTags: ['坚韧', '平凡'], sceneTags: ['开车', '思考'], moodScore: 5, neteaseId: 'c27' },
  { id: 'c28', title: '蓝莲花', artist: '许巍', album: '时光·漫步', emotionTags: ['自由', '向往'], sceneTags: ['开车', '旅行'], moodScore: 7, neteaseId: 'c28' },
  { id: 'c29', title: '曾经的你', artist: '许巍', album: '每一刻都是崭新的', emotionTags: ['热血', '青春'], sceneTags: ['开车', '运动'], moodScore: 8, neteaseId: 'c29' },
  { id: 'c30', title: '春风十里', artist: '鹿先森乐队', album: '所有的酒，都不如你', emotionTags: ['温柔', '诗意'], sceneTags: ['傍晚', '独处'], moodScore: 5, neteaseId: 'c30' },

  // 电子 / Ambient / 深度工作
  { id: 'e1', title: 'A Walk', artist: 'Tycho', album: 'Dive', emotionTags: ['专注', '漂浮'], sceneTags: ['工作', '学习'], moodScore: 6, neteaseId: 'e1' },
  { id: 'e2', title: 'Cirrus', artist: 'Bonobo', album: 'The North Borders', emotionTags: ['律动', '自然'], sceneTags: ['工作', '午后'], moodScore: 6, neteaseId: 'e2' },
  { id: 'e3', title: 'Open Eye Signal', artist: 'Jon Hopkins', album: 'Immunity', emotionTags: ['沉浸', '推进'], sceneTags: ['工作', '运动'], moodScore: 7, neteaseId: 'e3' },
  { id: 'e4', title: 'Silhouettes (I, II & III)', artist: 'Floating Points', album: 'Crush', emotionTags: ['实验', '流动'], sceneTags: ['工作', '深夜'], moodScore: 5, neteaseId: 'e4' },
  { id: 'e5', title: 'Two Thousand and Seventeen', artist: 'Four Tet', album: 'New Energy', emotionTags: ['温暖', '脉冲'], sceneTags: ['工作', '学习'], moodScore: 6, neteaseId: 'e5' },
  { id: 'e6', title: 'Raven — GoGo Penguin', artist: 'GoGo Penguin', album: 'v2.0', emotionTags: ['爵士', '电子'], sceneTags: ['工作', '雨天'], moodScore: 5, neteaseId: 'e6' },
  { id: 'e7', title: 'Space 1.8 — Nala Sinephro', artist: 'Nala Sinephro', album: 'Space 1.8', emotionTags: ['太空', '冥想'], sceneTags: ['冥想', '深夜'], moodScore: 2, neteaseId: 'e7' },
  { id: 'e8', title: 'Afterwork — Kiasmos', artist: 'Kiasmos', album: 'Kiasmos', emotionTags: ['冷峻', '节奏'], sceneTags: ['工作', '傍晚'], moodScore: 5, neteaseId: 'e8' },
  { id: 'e9', title: 'It Goes Like (Nanana)', artist: 'Peggy Gou', album: 'Nanana', emotionTags: ['舞曲', '轻快'], sceneTags: ['运动', '聚会'], moodScore: 8, neteaseId: 'e9' },
  { id: 'e10', title: 'Square', artist: 'Yerin Baek', album: 'Every letter I sent you.', emotionTags: ['慵懒', '午后'], sceneTags: ['午后', '咖啡'], moodScore: 6, neteaseId: 'e10' },
  { id: 'e11', title: 'A Moment Apart', artist: 'ODESZA', album: 'A Moment Apart', emotionTags: ['宏大', '感动'], sceneTags: ['运动', '旅行'], moodScore: 8, neteaseId: 'e11' },
  { id: 'e12', title: 'On My Knees', artist: 'RÜFÜS DU SOL', album: 'Surrender', emotionTags: ['迷幻', '奔跑'], sceneTags: ['运动', '夜跑'], moodScore: 7, neteaseId: 'e12' },
  { id: 'e13', title: 'Never Come Back', artist: 'Caribou', album: 'Suddenly', emotionTags: ['跳跃', '活力'], sceneTags: ['运动', '开车'], moodScore: 8, neteaseId: 'e13' },
  { id: 'e14', title: 'You & Me (Flume Remix)', artist: 'Disclosure', album: 'You & Me', emotionTags: ['电子', '坠落'], sceneTags: ['深夜', '聚会'], moodScore: 7, neteaseId: 'e14' },
  { id: 'e15', title: 'Delilah (pull me out of this)', artist: 'Fred again..', album: 'Actual Life 3', emotionTags: ['碎片', '真实'], sceneTags: ['深夜', '独处'], moodScore: 4, neteaseId: 'e15' },

  // 韩语 / K-pop / 独立
  { id: 'k1', title: '비행운', artist: 'MoonMoon', album: 'Life is Beauty Full', emotionTags: ['温柔', '治愈'], sceneTags: ['深夜', '独处'], moodScore: 4, neteaseId: 'k1' },
  { id: 'k2', title: 'Creepin\'', artist: 'Tabber, Paul Blanco, MISO', album: 'Creepin\'', emotionTags: ['暧昧', '夜晚'], sceneTags: ['深夜', '开车'], moodScore: 5, neteaseId: 'k2' },
  { id: 'k3', title: 'Hero', artist: 'Millic', album: 'Vida', emotionTags: ['自信', '节奏'], sceneTags: ['运动', '街头'], moodScore: 7, neteaseId: 'k3' },
  { id: 'k4', title: 'Wine', artist: 'Suran', album: 'Walkin\'', emotionTags: ['微醺', '慵懒'], sceneTags: ['深夜', '酒吧'], moodScore: 5, neteaseId: 'k4' },
  { id: 'k5', title: 'Tik Tak Tok', artist: '새라카젤', album: 'Tik Tak Tok', emotionTags: ['轻快', '俏皮'], sceneTags: ['学习', '晴天'], moodScore: 7, neteaseId: 'k5' },
  { id: 'k6', title: 'Ylang Ylang', artist: 'FKJ', album: 'Ylang Ylang', emotionTags: ['慵懒', '午后'], sceneTags: ['午后', '咖啡'], moodScore: 5, neteaseId: 'k6' },
  { id: 'k7', title: 'Harvest Moon', artist: 'Poolside', album: 'Harvest Moon', emotionTags: ['度假', '泳池'], sceneTags: ['晴天', '度假'], moodScore: 6, neteaseId: 'k7' },
  { id: 'k8', title: 'Tik Tak Ylang', artist: 'FKJ', album: 'Just Piano', emotionTags: ['钢琴', '安静'], sceneTags: ['学习', '雨天'], moodScore: 3, neteaseId: 'k8' },
  { id: 'k9', title: 'Bad', artist: 'Christopher', album: 'Bad', emotionTags: ['甜蜜', '轻快'], sceneTags: ['晴天', '恋爱'], moodScore: 8, neteaseId: 'k9' },
  { id: 'k10', title: 'Everyday', artist: 'WINNER', album: 'EVERYD4Y', emotionTags: ['元气', '日常'], sceneTags: ['晴天', '运动'], moodScore: 8, neteaseId: 'k10' },

  // 欧美流行 / 独立
  { id: 'w1', title: 'If', artist: 'Bread', album: 'Manna', emotionTags: ['温柔', '怀旧'], sceneTags: ['深夜', '独处'], moodScore: 4, neteaseId: 'w1' },
  { id: 'w2', title: 'Fade Into You', artist: 'Mazzy Star', album: 'So Tonight That I Might See', emotionTags: ['迷幻', '沉沦'], sceneTags: ['深夜', '雨天'], moodScore: 3, neteaseId: 'w2' },
  { id: 'w3', title: 'Wicked Game', artist: 'Chris Isaak', album: 'Heart Shaped World', emotionTags: ['性感', '危险'], sceneTags: ['深夜', '开车'], moodScore: 5, neteaseId: 'w3' },
  { id: 'w4', title: 'The Night We Met', artist: 'Lord Huron', album: 'Strange Trails', emotionTags: ['遗憾', '相遇'], sceneTags: ['深夜', '独处'], moodScore: 3, neteaseId: 'w4' },
  { id: 'w5', title: 'Nude', artist: 'Radiohead', album: 'In Rainbows', emotionTags: ['脆弱', '裸露'], sceneTags: ['深夜', '冥想'], moodScore: 2, neteaseId: 'w5' },
  { id: 'w6', title: 'Sign of the Times', artist: 'Harry Styles', album: 'Harry Styles', emotionTags: ['史诗', '告别'], sceneTags: ['深夜', '独处'], moodScore: 5, neteaseId: 'w6' },
  { id: 'w7', title: 'Dreams', artist: 'Fleetwood Mac', album: 'Rumours', emotionTags: ['洒脱', '流动'], sceneTags: ['晴天', '开车'], moodScore: 6, neteaseId: 'w7' },
  { id: 'w8', title: 'Just Getting Older', artist: 'Oasis', album: 'Heathen Chemistry', emotionTags: ['沧桑', '前行'], sceneTags: ['傍晚', '独处'], moodScore: 5, neteaseId: 'w8' },
  { id: 'w9', title: 'You\'ve Got a Friend', artist: 'Carole King', album: 'Tapestry', emotionTags: ['温暖', '陪伴'], sceneTags: ['雨天', '独处'], moodScore: 6, neteaseId: 'w9' },
  { id: 'w10', title: 'BIRDS OF A FEATHER', artist: 'Billie Eilish', album: 'HIT ME HARD AND SOFT', emotionTags: ['依恋', '轻盈'], sceneTags: ['午后', '独处'], moodScore: 5, neteaseId: 'w10' },
  { id: 'w11', title: 'No One But You', artist: 'Brad Paisley', album: 'Mud On The Tires', emotionTags: ['乡村', '简单'], sceneTags: ['晴天', '开车'], moodScore: 6, neteaseId: 'w11' },
  { id: 'w12', title: 'The Apl Song', artist: 'Black Eyed Peas', album: 'Elephunk', emotionTags: ['活力', '多元'], sceneTags: ['运动', '聚会'], moodScore: 8, neteaseId: 'w12' },
  { id: 'w13', title: '99 Problems', artist: 'Hugo', album: 'Old Tyme Religion', emotionTags: ['粗粝', '反叛'], sceneTags: ['开车', '街头'], moodScore: 7, neteaseId: 'w13' },
  { id: 'w14', title: 'when sunday comes around', artist: 'Marlon Funaki', album: 'sunday', emotionTags: ['慵懒', '周日'], sceneTags: ['早晨', '咖啡'], moodScore: 5, neteaseId: 'w14' },
  { id: 'w15', title: 'Somehow Familiar', artist: 'Fabrizio Paterlini', album: 'Autumn Stories', emotionTags: ['钢琴', '秋意'], sceneTags: ['雨天', '学习'], moodScore: 3, neteaseId: 'w15' },

  // 爵士 / 古典 / Neo-Classical
  { id: 'j1', title: 'River — 1/f', artist: 'Brian Eno', album: 'Ambient 4: On Land', emotionTags: ['环境', '冥想'], sceneTags: ['冥想', '深夜'], moodScore: 1, neteaseId: 'j1' },
  { id: 'j2', title: 'Untitled (In A Major)', artist: 'Stars of the Lid', album: 'And Their Refinement of the Decline', emotionTags: [' drone ', '漂浮'], sceneTags: ['冥想', '深夜'], moodScore: 1, neteaseId: 'j2' },
  { id: 'j3', title: 'Holding', artist: 'Grouper', album: 'Ruins', emotionTags: ['朦胧', '房间'], sceneTags: ['深夜', '独处'], moodScore: 2, neteaseId: 'j3' },
  { id: 'j4', title: 'dlp 1.1', artist: 'William Basinski', album: 'The Disintegration Loops', emotionTags: ['消逝', '时间'], sceneTags: ['深夜', '冥想'], moodScore: 1, neteaseId: 'j4' },
  { id: 'j5', title: 'Riverside', artist: 'Agnes Obel', album: 'Philharmonics', emotionTags: ['清冷', '河流'], sceneTags: ['雨天', '独处'], moodScore: 3, neteaseId: 'j5' },
  { id: 'j6', title: 'Should Have Known Better', artist: 'Sufjan Stevens', album: 'Carrie & Lowell', emotionTags: ['脆弱', '回忆'], sceneTags: ['深夜', '独处'], moodScore: 2, neteaseId: 'j6' },
  { id: 'j7', title: 'Mai mai', artist: 'Marco Cionini', album: 'Mai mai', emotionTags: ['意大利', '温柔'], sceneTags: ['午后', '咖啡'], moodScore: 5, neteaseId: 'j7' },
  { id: 'j8', title: 'Gymnopédie No.1', artist: 'Erik Satie', album: 'Gymnopédies', emotionTags: ['古典', '安静'], sceneTags: ['学习', '冥想'], moodScore: 2, neteaseId: 'j8' },
  { id: 'j9', title: 'Clair de Lune', artist: 'Claude Debussy', album: 'Suite bergamasque', emotionTags: ['月光', '梦幻'], sceneTags: ['深夜', '独处'], moodScore: 2, neteaseId: 'j9' },
  { id: 'j10', title: 'The Four Seasons: Winter', artist: 'Vivaldi', album: 'The Four Seasons', emotionTags: ['古典', '凛冽'], sceneTags: ['冬天', '独处'], moodScore: 3, neteaseId: 'j10' },

  // Post-Punk / J-Rock / 另类
  { id: 'r1', title: ' running up that hill', artist: 'Kate Bush', album: 'Hounds of Love', emotionTags: ['史诗', '奔跑'], sceneTags: ['运动', '夜晚'], moodScore: 7, neteaseId: 'r1' },
  { id: 'r2', title: 'Love Will Tear Us Apart', artist: 'Joy Division', album: 'Closer', emotionTags: ['冰冷', '分离'], sceneTags: ['深夜', '雨天'], moodScore: 2, neteaseId: 'r2' },
  { id: 'r3', title: 'Ageispolis', artist: 'Aphex Twin', album: 'Selected Ambient Works 85-92', emotionTags: ['电子', '怪异'], sceneTags: ['工作', '深夜'], moodScore: 5, neteaseId: 'r3' },
  { id: 'r4', title: 'Teardrop', artist: 'Massive Attack', album: 'Mezzanine', emotionTags: ['trip-hop', '心跳'], sceneTags: ['深夜', '独处'], moodScore: 3, neteaseId: 'r4' },
  { id: 'r5', title: 'Glory Box', artist: 'Portishead', album: 'Dummy', emotionTags: ['慵懒', '危险'], sceneTags: ['深夜', '酒吧'], moodScore: 4, neteaseId: 'r5' },
  { id: 'r6', title: 'First Love/Late Spring', artist: 'Mitski', album: 'Bury Me at Makeout Creek', emotionTags: ['爆发', '青春'], sceneTags: ['深夜', '独处'], moodScore: 5, neteaseId: 'r6' },
  { id: 'r7', title: 'Nobody', artist: 'Mitski', album: 'Be the Cowboy', emotionTags: ['荒诞', '孤独'], sceneTags: ['深夜', '独处'], moodScore: 4, neteaseId: 'r7' },
  { id: 'r8', title: 'Pink + White', artist: 'Frank Ocean', album: 'Blonde', emotionTags: ['温柔', '回忆'], sceneTags: ['晴天', '独处'], moodScore: 5, neteaseId: 'r8' },
  { id: 'r9', title: 'Self Control', artist: 'Frank Ocean', album: 'Blonde', emotionTags: ['克制', '夏日'], sceneTags: ['深夜', '独处'], moodScore: 4, neteaseId: 'r9' },
  { id: 'r10', title: 'Motion Picture Soundtrack', artist: 'Radiohead', album: 'Kid A', emotionTags: ['告别', '竖琴'], sceneTags: ['深夜', '冥想'], moodScore: 2, neteaseId: 'r10' },

  // 白噪音 / 功能性
  { id: 'n1', title: '下雨白噪音', artist: 'MiMo FM', album: '环境音', emotionTags: ['安静', '专注'], sceneTags: ['学习', '睡眠'], moodScore: 1, neteaseId: 'n1' },
  { id: 'n2', title: '咖啡厅环境音', artist: 'MiMo FM', album: '环境音', emotionTags: ['温暖', '专注'], sceneTags: ['学习', '工作'], moodScore: 3, neteaseId: 'n2' },
  { id: 'n3', title: '森林鸟鸣', artist: 'MiMo FM', album: '环境音', emotionTags: ['自然', '清醒'], sceneTags: ['早晨', '冥想'], moodScore: 4, neteaseId: 'n3' },
  { id: 'n4', title: '海浪声', artist: 'MiMo FM', album: '环境音', emotionTags: ['宽广', '呼吸'], sceneTags: ['冥想', '睡眠'], moodScore: 2, neteaseId: 'n4' },
  { id: 'n5', title: '篝火声', artist: 'MiMo FM', album: '环境音', emotionTags: ['温暖', '陪伴'], sceneTags: ['深夜', '独处'], moodScore: 3, neteaseId: 'n5' },
]
